In [1]:
import pandas as pd
import datetime as dt
import re

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options


from bs4 import BeautifulSoup

In [32]:
#python 3.11.5
#selenium==4.24.0
#Flask-SQLAlchemy==2.5.1
#pandas==2.0.3
#bs4==0.0.2

<h4> Selenium Driver for Firefox </h4>

In [2]:
driver=webdriver.Firefox()

driver.get('https://www.tesourodireto.com.br/titulos/precos-e-taxas.htm')

data = driver.page_source

<h3> bs4 soup </h3>

In [33]:
soup = BeautifulSoup(data, 'html.parser')

soup = soup.find_all('table')[0] # for not duplicating data; more tables were found

In [5]:
# scraping with bs4;

row_set = []
for row in soup.find_all('tr'):
    
    col_set = []

    for td in row.find_all('td'):
        col_set.append(td.text.strip())
    
    # regex to clean the data;
    try:
        col_set[0] = re.search('[a-zA-Z+ ]+(\w*)' , col_set[0]).group().strip()
    except:
        print('hm oops, got some error', col_set)
        
    
    if len(col_set) >= 6: # slicing relevant and irregular data;
        col_set.pop(2)

    row_set.append(col_set)


# small cleaning 
 
try:    row_set.remove([])
except: None

hm oops, got some error []

In [6]:
df = pd.DataFrame(row_set)
df.head(3)

,0,1,2,3,4,5
0,Tesouro Prefixado,"12,90%","R$ 767,34",01/01/2027,Simule o investimento,None
1,Tesouro Prefixado,"13,02%","R$ 471,03",01/01/2031,Simule o investimento,None
2,Tesouro Prefixado,"12,83%","R$ 881,22",01/01/2035,Simule o investimento,None

In [7]:
# discarting useless cols;

df =df.drop(columns = [4,5])

In [8]:
# renaming cols 

columns = ['titulo', 'taxa', 'pu', 'vencimento']
df.columns = columns

In [9]:
df = df.dropna(how = 'all')

### Cleaning and Transforming

In [10]:
pd.set_option('display.max_rows', 1000)

display(df.head(3))
df.dtypes

              titulo    taxa         pu  vencimento
0  Tesouro Prefixado  12,90%  R$ 767,34  01/01/2027
1  Tesouro Prefixado  13,02%  R$ 471,03  01/01/2031
2  Tesouro Prefixado  12,83%  R$ 881,22  01/01/2035

titulo        object
taxa          object
pu            object
vencimento    object
dtype: object

In [11]:
# numeric dtypes;

df.loc[:, 'pu'] = df.pu.str.replace("R$ ", '')
df.loc[:, 'pu'] = df.pu.str.replace('.', '')
df.loc[:, 'pu'] = df.pu.str.replace(',', '.')
df['pu'] = df.pu.astype(float)

In [12]:
## datetime;

df['vencimento'] = df.vencimento.apply(lambda x: dt.datetime.strptime(x, '%d/%m/%Y'))

In [13]:
display(df.head(3))
df.dtypes

              titulo    taxa      pu vencimento
0  Tesouro Prefixado  12,90%  767.34 2027-01-01
1  Tesouro Prefixado  13,02%  471.03 2031-01-01
2  Tesouro Prefixado  12,83%  881.22 2035-01-01

titulo                object
taxa                  object
pu                   float64
vencimento    datetime64[ns]
dtype: object

In [14]:
# test if there is any duplicated data;

assert df.duplicated(subset=['titulo', 'vencimento'], keep=False).sum() == 0

In [15]:
# Today's date to register alongside the values of the scraped data;
d0 = dt.date.today()

df['data'] = d0
df.head()

              titulo             taxa        pu vencimento        data
0  Tesouro Prefixado           12,90%    767.34 2027-01-01  2024-10-20
1  Tesouro Prefixado           13,02%    471.03 2031-01-01  2024-10-20
2  Tesouro Prefixado           12,83%    881.22 2035-01-01  2024-10-20
3      Tesouro Selic  SELIC + 0,0503%  15484.70 2027-03-01  2024-10-20
4      Tesouro Selic  SELIC + 0,1414%  15408.51 2029-03-01  2024-10-20

<h3> Putting On DB Postgres </h3>

<h5> DB Credentials </h5>

In [16]:
from sqlalchemy import text, create_engine


db_txt = input('Digite o caminho do arquivo com a URL do banco de dados: ')

with open(db_txt, 'r') as f:
    uri = f.readline()[:-1] # to remove \n

In [17]:
engine = create_engine(uri)

postgresql+psycopg2://peon:Gotadelimao123@localhost:5432/carteira

<h5> Create a table to store scraped data </h5>

In [18]:
query = """ CREATE TABLE br_treasury_titles(
                            data date,
                            titulo varchar(64), 
                            taxa varchar(64), 
                            pu numeric(7,2), 
                            vencimento date
                            )"""

cursor = engine.connect()


try:
    cursor.execute(text(query))
    cursor.commit()
    cursor.close()

except:
    print("Table already exists in DB. Drop or switch to another db.")

Table already exists in DB. Drop or switch to another db.

In [25]:
# ADD Constraint for unique title, expire date and day of scraping

with engine.connect() as con:

    con.execute(text("""ALTER TABLE br_treasury_titles ADD CONSTRAINT "uniTiDaVen" UNIQUE (titulo, vencimento, data)"""))
    con.commit()

In [28]:
# Inserting the Data (load phase); 

with engine.connect() as con:

    try:
        df.to_sql(name = 'br_treasury_titles', 
              con=con,
              schema='public',
              if_exists='append',
              index=False)
        
    except:
        print('there is duplicated data')
        #duplicated = True

there is duplicated data

<h3> ### </h3>